### ISSUE TITLE
Inbuilt ESS similar functionality.

### ISSUE THREAD

**Issue by vspinu** [myuhe/ess-R-object-popup.el#1]
Hi, there is an inbuilt similar functionality in ESS, it is bound to C-c C-d C-e. Afterward you can cycle "electrically" with C-e. May be it's worth adding a note on this in the comment.

**Comment by myuhe** [comment]
@vitoshka I don't think  ess-R-object-popup has similar functionality.  ess-R-object-popup use popup.el, and popup.el smart popup library. I hope ESS merge ess-R-object-popup.el.

**Comment by vspinu** [comment]
> > Yuhei Maeda notifications@github.com
> > on Mon, 29 Apr 2013 05:37:10 -0700 wrote:
> 
> @vitoshka I don't think ess-R-object-popup has similar functionality.
> ess-R-object-popup use popup.el, and popup.el smart popup library. I
> hope ESS merge ess-R-object-popup.el.

Pop-ups are not that convenient as electric buffers IMO. With electric
buffer you can actually switch to the buffer and investigate your object
there.

**Comment by myuhe** [comment]
@vitoshka
popup.el has cascade menu. If you want to many information, you can show information in  cascade menu .
In detail, https://github.com/auto-complete/popup-el
